name = "UsingAll"
uuid = "1c35494a-ca84-4a81-96ab-c66f6554cc27"
authors = ["Knut Andreas Meyer and contributors"]
version = "0.1.0"

[compat]
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TestPackage = "2449ae4a-c732-4aef-a98c-3f690a9dcc0a"

[targets]
test = ["Test", "TestPackage"]

[sources]
TestPackage = {path = "test/TestPackage"}
